name: trivial-services
proxy:
  appserver:
    - trivial-services.lndo.site
services:
  appserver:
    type: nginx
    ssl: true
    webroot: www
    config:
      server: config/server.conf
    overrides:
      services:
        environment:
          THING: STUFF
        ports: ['8080:80']
